{{- if and (not .Values.existingSecret) .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "status-poller.fullname" . }}
  labels:
    {{- include "status-poller.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
